name: ğŸ› Eslint Check
on:
  push:
    branches:
      - main
jobs:
  ğŸ•µï¸â€â™€ï¸ Check Code Quality:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v2
      - name: ğŸ“¦ Install Dependencies
        run: yarn install
      - name: ğŸ§¹ Run Eslint
        run: yarn run analyze
